### ISSUE TITLE
ContextErrorException in ps_googleanalytics.php line 328

### ISSUE THREAD

**Issue by voznik** [PrestaShop/ps_googleanalytics#1]
hi! I'm using this module on PS 1.7.1.1 live setup, and getting this error:
`ContextErrorException in ps_googleanalytics.php line 328: Notice: unserialize(): Error at offset 0 of 375 bytes`

![image](https://user-images.githubusercontent.com/5063203/26899219-2843a646-4bd7-11e7-97fe-8561d79436b2.png)

any suggestions?

**Comment by dominikse** [comment]
I'm experiencing the same issue (also 1.7.1.1) on checking out the cart (after confirming the shipping method) this error occurs. It works fine once the google analytics module is disabled.

Would be great if anyone has an idea on how to solve this issue!

**Comment by cedricfontaine** [comment]
I pushed a modification in the dev branch. Could you test it ?
