### ISSUE TITLE
No HTTP response detected on admin page

### ISSUE THREAD

**Issue by psxtavi** [PrestaShop/ps_googleanalytics#11]
Tag Assistant reports the following error when I am logged in on the admin page: "No HTTP response detected" 
This is the code: 

<script type="text/javascript">

   (window.gaDevIds=window.gaDevIds\|\|[]).push('d6YPbH');
   (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]\|\|function(){
   (i[r].q=i[r].q\|\|[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
   m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
   })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
   ga('create', 'UA-*********-1', 'auto');
   ga('set', 'nonInteraction', true);
   ga('require', 'ec');

 </script>

Prestashop version is 1.7.3.1 with the default theme and demo content. It is a fresh install.
The module for google analytics is 3.0.4

**Comment by cedricfontaine** [comment]
No tracking is sent on the admin back end.

**Comment by Hlavtox** [comment]
@khouloudbelguith Hi, can you reopen this issue and ping somebody from the team who takes care of this module? :-)

The module does not track at all at admin pages. I don't know why @cedricfontaine closed this.

Thank you!
