### ISSUE TITLE
updated to 3.1.3, no tracking at all (No HTTP response detected)

### ISSUE THREAD

**Issue by masiorama** [PrestaShop/ps_googleanalytics#29]
Hello there, I just installed the update 3.1.3 from 3.1.1 on PS 1.7.5, and suddenly no analytics tracking is working. 
The module is correctly configurated. 
Checking with google tag chrome extension the error shown is `No HTTP response detected`.

Searching in the page source I can see this analytics snippet:

```
(window.gaDevIds=window.gaDevIds\|\|[]).push('d6YPbH');

 (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]\|\|function(){
 (i[r].q=i[r].q\|\|[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
 })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  
 ga('create', 'UA-********-1', 'auto');
 ga('set', 'anonymizeIp', true);
  
 ga('require', 'ec');
```

Is this a bug? Any suggestion to make the tracking work again?

**Comment by khouloudbelguith** [comment]
Hi @masiorama,

I tried with PS1.7.5.0 & the ps_googleanalytic v3.1.3 and I did not manage to reproduce the issue.
![image](https://user-images.githubusercontent.com/16067358/51620746-5583b980-1f33-11e9-9770-94a7cc6f83ee.png)
Thanks!

**Comment by masiorama** [comment]
Hi @khouloudbelguith, can you please show me the generated source code of that page, like I did?
I want to check the differences. Thanks!

**Comment by khouloudbelguith** [comment]
Hi @masiorama,

Here's the view_source

[view_source.html.zip](https://github.com/PrestaShop/ps_googleanalytics/files/2788331/view_source.html.zip)
Thanks!

**Comment by masiorama** [comment]
Thank you very much. Looking at your code there is something strange, since, copy-pasting, it is:

```

ga('create', 'UA-133013050-1', 'auto');
ga('set', 'userId', '3');
ga('set', 'anonymizeIp', true);
ga('require', 'ec');
ga('create', 'UA-133013050-1', 'auto');
ga('set', 'userId', '3');
ga('set', 'anonymizeIp', true);
ga('require', 'ec');

```
The code is doubled, somehow.
Despite that, the only difference is that your have that userId set, while I have it not.

I checked my module conf, and it is set like this:
`Activate userId tracking: YES` 
`Anonymize IP: YES`

What is wrong on your opinion?
Why is your tracking working without sending a pageview to GA?
Thanks for your assistance, much appreciated!

**Comment by khouloudbelguith** [comment]
@masiorama, about the double code, it is my bad.
About your issue, if try to uninstall the module (remove the ps_googleanalytics folder from your Project_Folder/modules/ & install it again, have you the same issue again?
Thanks!

**Comment by masiorama** [comment]
It does work! I guess something was cached, or maybe the database?
You can close the issue.
Thank you very much again!

**Comment by khouloudbelguith** [comment]
@masiorama, thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
