### ISSUE TITLE
Installing v.1.8 over Prestashop 1.5.6.0 not work

### ISSUE THREAD

**Issue by jpefranco** [PrestaShop/ps_googleanalytics#32]
Hi, 

First of all thanks for your work. I've just downloaded the v1.8-ganalytics.zip file, but when I try to install it I have got an error that says: 

The following module(s) were not installed successfully:
- ganalytics : 
The version of your module is not compliant with your PrestaShop version.

My Prestashop version is 1.5.6.0 and I'm using the v1.5-ganalytics. I'd like to update it because the conversion ratio in Google Analytics is not working.

Can you help me, please? 

Thank you in advance.

Regards,
Jesus

**Comment by matks** [comment]
Hi, I'm sorry but v1.8 of this module was released a very long time ago, so long that it cannot even be found in [this repository releases](https://github.com/PrestaShop/ps_googleanalytics/releases). It's hard to help you without even the code 😞 .

Also if you are running PS 1.5.6 please be aware that this version is not maintained anymore, and it is not compatible with current supported php versions (php 7.1 and higher), so you might be vulnerable to unpatched security flaws in either the old version of php you are using or the old version of prestashop you are using. You can find more informations here: https://www.prestashop.com/en/blog/php-5-6-online-store-security

*That is, except if you have updated your code to use a more recent php version

**Comment by jpefranco** [comment]
Okay, I understand it. Thank you for your fast response. 

We really have some custom functionality so it's not easy to update it easy, but I know we have to do it.

**Comment by colinegin** [comment]
Thank you for your understanding, I close this issue then.
