### ISSUE TITLE
The module should not manage ps_featuredproducts hooking

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/ps_googleanalytics#33]
The hookdisplayHome method calls $this->isModuleEnabled('ps_featuredproducts')
This force the hooking of  ps_featuredproducts module to the 'displayHome' hook :
https://github.com/PrestaShop/ps_googleanalytics/blob/ea820dd8fa50fb0b41ba7d5ff6fa0d32f126d207/ps_googleanalytics.php#L493

The google analytics module should not take care ok hooking of other modules.

**Comment by khouloudbelguith** [comment]
Related to: https://github.com/PrestaShop/PrestaShop/issues/13371

**Comment by bguerbet** [comment]
When I comment this line nothing appear on the website...
Maybe I didn't undurstand what we need to do ?
Please explain to me what to do with the line 493 !

**Comment by netraagal** [comment]
@bguerbet what do you mean by nothing appear ?

When comparing the [previous function](https://github.com/PrestaShop/ganalytics/blob/a823fe01de76220ed39c8018c422c5cf32e32c77/ganalytics.php#L448) in old googleanalytics, we checked **if** module what hooked with `$module->isRegisteredInHook('home')`.

Why now in 1.7 the code force the hook instead of just checking if it's hooked like in 1.6 and previous ?

**Comment by bguerbet** [comment]
Pour Google Analytics v3.2.0 voici la modification dans "modules/ps_googleanalytics/ps_googleanalytics.php" ligne 524 à 526

![Dégreffer module qui revient systématiquement - PrestaShop pour les développeurs - dans Ps_Googleanalytics php ligne 524](https://user-images.githubusercontent.com/44406251/72605986-0db52980-391e-11ea-8491-0d160d61dbd4.JPG)

**Comment by jf-viguier** [comment]
@bguerbet fait une pull request

**Comment by sharkooon** [comment]
Please update this as soon as possible! Don't want featured products as hook on displayHome

**Comment by matks** [comment]
Indeed I see no logic into current implementation of `ModuleHandler::isModuleEnabled`
```
public function isModuleEnabled($moduleName)
    {
        $module = Module::getInstanceByName($moduleName);

        if (false === $module) {
            return false;
        }

        if (false === Module::isInstalled($moduleName)) {
            return false;
        }

        if (false === $module->active) {
            return false;
        }

        return $module->registerHook('displayHome');
    }
```

This logic would be better renamed `ModuleHandler::hookToDisplayHomeIfItCanBeHooked`

**Comment by matks** [comment]
PR is here https://github.com/PrestaShop/ps_googleanalytics/pull/73

**Comment by lolodeville** [comment]
The bug is back...
Hi. I have made an update on Prestashop 1.7.6.8 with google analytics v4.0.0
The problem is back. and I can't use the "return True" option, because the file has changed.
I'm not devlopper... Could you tell me how I can do ? Thanks

**Comment by Gemma97** [comment]
Hi, same problem here, any idea on how to fix it or when is it going to be fixed?

**Comment by akorkmaz66** [comment]
Uncomment this function in ps_googleanalytics.php

Starts normally at line 117

 public function hookDisplayHome()
    {
        $hook = new PrestaShop\Module\Ps_Googleanalytics\Hooks\HookDisplayHome($this, $this->context);

        return $hook->run();
    }*/

**Comment by matks** [comment]
Fixed in https://github.com/PrestaShop/ps_googleanalytics/pull/73 and delivered in module 4.1.0 version
