### ISSUE TITLE
Connexion prestashop with analytics

### ISSUE THREAD

**Issue by shop-sonate** [PrestaShop/ps_googleanalytics#39]
Hello 
I tried as many ways I can to connect my prestashop eshop with analytics, but it seems to be impossible for me ... The prestashop addons team told me I "have a problem with a native module or partner module" and suggest me to post my problem here.. 
I still don't know how to do to find a solution .. Can somebody help me please ?

Thanks a lot
Best regards

**Comment by colinegin** [comment]
Hello @shop-sonate ,

Sorry for the late reply, could you give us more information on your store version, the steps you followed, etc. so that we can test it on our side ?

Thanks

**Comment by matks** [comment]
Closing issue as no answer from author
