### ISSUE TITLE
ContextErrorException in ps_googleanalytics.php line 281

### ISSUE THREAD

**Issue by patryk-uszynski** [PrestaShop/ps_googleanalytics#4]
This exception occurs in `hookdisplayOrderConfirmation`:
```
ContextErrorException in ps_googleanalytics.php line 281:
Notice: Undefined index: order
```
Works fine after changing `order` to `objOrder`
```
$order = $params['objOrder'];
```

**Comment by cedricfontaine** [comment]
Which version of prestashop are you using ?

**Comment by patryk-uszynski** [comment]
@cedricfontaine 1.7.1.0

**Comment by patryk-uszynski** [comment]
It was problem with incorrectly defined hook params in payment module
