### ISSUE TITLE
Checkout Step is not working due to Tools::getValue('step') in 1.7.6

### ISSUE THREAD

**Issue by dgonzalez360** [PrestaShop/ps_googleanalytics#48]
Hi, 

The module is no longer tracking the checkout steps due to the lack of step variable on the checkout process. 

Is there a way to get the current step from the order controller?

**Comment by matks** [comment]
https://github.com/PrestaShop/PrestaShop/pull/15176/files solves this for 1.7.7 but you should be able to copy the logic for your module. You fetch `getSteps()` then iterate to find the current.

**Comment by dgonzalez360** [comment]
> https://github.com/PrestaShop/PrestaShop/pull/15176/files solves this for 1.7.7 but you should be able to copy the logic for your module. You fetch `getSteps()` then iterate to find the current.

Thank you for your reply !. Can you guide me a bit how to get the steps from the module ? I tried using $this->context->controller-checkoutPRocess without any luck. 

Thank you for your help!

**Comment by matks** [comment]
Now I remember: `checkoutProcess` cannot be retrieved before 1.7.7 because it was a private or protected variable. We had the same issue for [ps_checkout](https://github.com/PrestaShopCorp/ps_checkout) so we used a trick to fetch the steps even without the fix in 1.7.7 .
See https://github.com/PrestaShopCorp/ps_checkout/blob/master/ps_checkout.php#L577
```
private function getAllOrderSteps()
    {
        $isPrestashop177 = version_compare(_PS_VERSION_, '1.7.7.0', '>=');

        if (true === $isPrestashop177) {
            return $this->context->controller->getCheckoutProcess()->getSteps();
        }

        /* Reflect checkoutProcess object */
        $reflectedObject = (new ReflectionObject($this->context->controller))->getProperty('checkoutProcess');
        $reflectedObject->setAccessible(true);

        /* Get Checkout steps data */
        $checkoutProcessClass = $reflectedObject->getValue($this->context->controller);

        return $checkoutProcessClass->getSteps();
    }
```
Basically we use [PHP Reflection](https://www.php.net/manual/en/book.reflection.php) to be given access to the variable even though we should not be able to access it.

Since PS 1.7.7 we dont need to do this any more 😊

**Comment by Matt75** [comment]
> Now I remember: `checkoutProcess` cannot be retrieved before 1.7.7 because it was a private or protected variable. We had the same issue for [ps_checkout](https://github.com/PrestaShopCorp/ps_checkout) so we used a trick to fetch the steps even without the fix in 1.7.7 .
> See https://github.com/PrestaShopCorp/ps_checkout/blob/master/ps_checkout.php#L577
> 
> ```
> private function getAllOrderSteps()
>     {
>         $isPrestashop177 = version_compare(_PS_VERSION_, '1.7.7.0', '>=');
> 
>         if (true === $isPrestashop177) {
>             return $this->context->controller->getCheckoutProcess()->getSteps();
>         }
> 
>         /* Reflect checkoutProcess object */
>         $reflectedObject = (new ReflectionObject($this->context->controller))->getProperty('checkoutProcess');
>         $reflectedObject->setAccessible(true);
> 
>         /* Get Checkout steps data */
>         $checkoutProcessClass = $reflectedObject->getValue($this->context->controller);
> 
>         return $checkoutProcessClass->getSteps();
>     }
> ```
> 
> Basically we use [PHP Reflection](https://www.php.net/manual/en/book.reflection.php) to be given access to the variable even though we should not be able to access it.
> 
> Since PS 1.7.7 we dont need to do this any more 😊

Maybe this can be better : 
https://ocramius.github.io/blog/accessing-private-php-class-members-without-reflection/

**Comment by matks** [comment]
Looks like this issue does not need more items so I close it 👍

**Comment by HartLarsson** [comment]
there is no possibility to implement on 1.7.6 branch? all "Checkout Behavior Analysis" are broken totally
