### ISSUE TITLE
PS 1.7.6.5 - no info on BO

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/ps_googleanalytics#51]
Seems that for some reason on 1.7.6.5 version the module v3.2.0 not bring on BO any information in the control panel:

![image](https://user-images.githubusercontent.com/16102074/81442573-261ead80-9174-11ea-84b1-2af2081466f6.png)

![image](https://user-images.githubusercontent.com/16102074/81442635-43537c00-9174-11ea-9121-cad81d312f79.png)

**Comment by Quetzacoalt91** [comment]
Hi, 

These lines are not related to this modules, but respectively to these ones:
* [gapi](https://github.com/PrestaShop/gapi) <-- Responsible in displaying data from analytics on the dashboard
* [statsforecast](https://github.com/PrestaShop/statsforecast)
* [statsvisits](https://github.com/PrestaShop/statsvisits)

As long as the data is properly transmitted to your google analytics dashboard, this module is working properly. I'm closing this issue and recommend to reopen one on https://github.com/PrestaShop/PrestaShop/issues/new/choose.
