### ISSUE TITLE
Prestashop 1.7.6.5...no module analytics

### ISSUE THREAD

**Issue by docjivaro** [PrestaShop/ps_googleanalytics#54]
Hello
In catalogue module, I have not the google analytics module. I dowloaded ps_googleanalytics-master on github, but failure in installa module, Itried to rename it in ps_googleanalytics, same result.
Do you know if there is any possibility to download it for 1.7.6.5 ?

Many thanks

**Comment by aldo-israel** [comment]
Did you find a solution?

I have the same issue.

**Comment by docjivaro** [comment]
Yes !
In prestashop forum :
"in the layout-both-columns.tpl  file located in the ./themes/classic/templates/layouts/ directory"

"

So What I did is add this code in my header.tpl file in template/_partials but don't forget to add {literal}{/literal} at the starting and closing of the tag else you'll get a blank white page.

{literal} 
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-134165817-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-*********-*');
</script>  {/literal}"


and of course before and after, empty the cache..

________________________________
De : aldo-israel <notifications@github.com>
Envoyé : jeudi 16 juillet 2020 03:49
À : PrestaShop/ps_googleanalytics <ps_googleanalytics@noreply.github.com>
Cc : docjivaro <docjivaro@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [PrestaShop/ps_googleanalytics] Prestashop 1.7.6.5...no module analytics (#54)


Did you find a solution?

I have the same issue.

**Comment by matks** [comment]
Looks like issue is fixed so I close it 😉
