### ISSUE TITLE
ReferenceError: Can't find variable: GoogleAnalyticEnhancedECommerce after upgrade to v4.0

### ISSUE THREAD

**Issue by fire2** [PrestaShop/ps_googleanalytics#58]
Running current version of Prestashop 1.7.6.7
Upgraded ps_googleanalytics module to v4.0.0 released 2 days ago.
Theme is a child theme of the default classic with minor overrides. 

The module throws console error ReferenceError: Can't find variable: GoogleAnalyticEnhancedECommerce. It seems like the GoogleAnalyticActionLib.js file is not being loaded, although the module is hooked into the 'header' hook. Tried resetting the module but that did not help. 

Site URL: https://mercerie-voilage.com/fr/

**Comment by matks** [comment]
If the issue happens because of overrides and/or custom theme, I believe the need for update must be done within these overrides and/or custom themes 🤔  ?
