### ISSUE TITLE
Google Analytics | actionCartSave

### ISSUE THREAD

**Issue by manfield** [PrestaShop/ps_googleanalytics#6]
I report the issue on github.
I opened it on forge, but still not considered.

http://forge.prestashop.com/browse/PNM-3928

E-commerce actions addToCart/removeFromCart are not tracked when ajax approach is used (and it is used by default theme itself, in PS 1.7).
In order to manage actions performed via Ajax, the module stores a cookie.
Thus when the page is reloaded the cookie is checked and sent to the browser.
Then the cookie is processed by the frontend scripts, decoded and Google Analytics Action performed.
BUT!
Module's author stores the cookie on hookactionCartSave.
I checked the cookie at this point and the value $this->context->cookie->ga_cart contains a valid object.
When the user reloads the page, hookdisplayFooter is called and the cookie should be passed back to the browser.
The problem is that the cookie is lost and $this->context->cookie->ga_cart is null (inside this hook)
This causes the problem with addProduct event, that is not sent to Google Analytics.

It seems that cookies are reset after cart saving.
If I put a die() after hookactionCartSave latest code line and then reload the page,
the cookie is still there and actions are correctly performed.
Otherwise the cookie is wiped away by another call.

This issue affects a fresh install of the platform (1.7.x).

**Comment by idealdesigns** [comment]
I confirm the issues exists, ADD TO CART is not tracked at all. its advertised its working on the page. Where are the developers?!!!!!

**Comment by cedricfontaine** [comment]
Could you try to modify this in hookDispayFooter
if (isset($this->context->cookie->ga_cart)) {
by
$controller_name = Tools::getValue('controller');
if (isset($this->context->cookie->ga_cart) && $controller_name!='product') {

It should fix the problem

**Comment by manfield** [comment]
Yes, I confirm it makes the job.
When will it be available on official release? or, at least pushed in the dev branch?

**Comment by blaher** [comment]
@cedricfontaine Is there a release timeframe on this or could yourself or @manfield specify what file that line is in so others may fix this issue? I'm running across the same thing and it's very inconvenient for my GA data to see what's going on with visitor behavior.

**Comment by cedricfontaine** [comment]
There is a new release coming out and it should fix it. You could try it on the dev branch.

**Comment by blaher** [comment]
@cedricfontaine I tested with what was in the dev branch and there was still no event fired. I then compared a diff of what I had previous to what there is now, and there were no changes. Do you need help with it? I can possibly help contribute. I'm not sure where the 'GoogleAnalyticEnhancedECommerce' JS object comes from though.

**Comment by blaher** [comment]
I did a little debugging. I'm pretty new to Prestashop just to note. When I click add to cart, it looks like AJAX POSTs to the same page. That is when the script is outputted, so it never runs that javascript to fire the addtocart event. Especially since your script deletes that database entry after it displays the script the first and only time. I made a pretty bad fix by just wrapping the inside of `hookdisplayFooter()` with `if ($_SERVER['REQUEST_METHOD'] === 'GET')`. I however do not know the full impact this would cause and would not say it's an ideal fix. Especially since if they add to cart and then leave the page, the script never gets ran unless they visit another page.

**Comment by cedricfontaine** [comment]
Sorry, it's now on dev branch.

**Comment by MathiasReker** [comment]
Is this bug fixed?

**Comment by matks** [comment]
It seems issue is fixed in v4.0.0. Feel free to reopen an issue if you find usecase where issue is still observable.
