### ISSUE TITLE
Bad date_add

### ISSUE THREAD

**Issue by Daaaaad** [PrestaShop/ps_googleanalytics#62]
Hello,

I just installed and configured the module on a PS 1.6.1.24.

When I pass an order the data registered in ps_ganalytics is the following : 

<img width="993" alt="Capture d’écran 2020-08-19 à 11 36 06" src="https://user-images.githubusercontent.com/167037/90618692-a2636b00-e210-11ea-86d3-eedfd94b52d3.png">

"date_add" contain a bad value... like if the NOW() function was not interpreted.

### How to reproduce

1. Install ps_googleanalytics v4.0.0
2. Set it up
3. Create an order from FO
4. Open a SQL client (phpMyAdmin, Sequel Pro ...) and look at content of SQL table `ps_ganalytics`
5. See content of column `date_add` is 0000-00-00 00:00:00

**Comment by Daaaaad** [comment]
The SQL query executed to add those rows is : 

INSERT IGNORE INTO `ps_ganalytics` (`id_order`, `id_shop`, `sent`, `date_add`) VALUES ('4405', '1', '0', 'NOW()')

In this case NOW() is not interpreted correctly 😞

**Comment by matks** [comment]
I confirm this issue.

**Comment by matks** [comment]
I submitted a PR to fix this bug https://github.com/PrestaShop/ps_googleanalytics/pull/68

**Comment by Daaaaad** [comment]
Hello @matks, will you fix it in other places?

**Comment by matks** [comment]
> Hello @matks, will you fix it in other places?

I guess I have no choice, right 😛  ?

**Comment by Shoprunners** [comment]
Hi, without bugfixing the other places, this module will not work since there is no order data in the database.

**Comment by matks** [comment]
Fix finally available in new module version https://github.com/PrestaShop/ps_googleanalytics/releases/tag/v4.1.0
