### ISSUE TITLE
Cannot install on 1.7.7.5

### ISSUE THREAD

**Issue by rbuelund** [PrestaShop/ps_googleanalytics#96]
I have downloaded the package from github, but I cannot install it in my shop ??

**Comment by rbuelund** [comment]
It says "Not a valid module zip"

**Comment by matks** [comment]
Hi, the 4.0.0 ZIP is a file created by GitHub that contains the source code, it's not suitable to use inside a shop. You need to run `composer install` to build a production-ready module.

**Comment by eugentum** [comment]
> Hi, the 4.0.0 ZIP is a file created by GitHub that contains the source code, it's not suitable to use inside a shop. You need to run `composer install` to build a production-ready module.

Sorry, how do I do this?

**Comment by matks** [comment]
@rbuelund Hi @eugentum we released today ps_googleanalytics v4.1.0 module.

We attached a production-ready ZIP to the release, you can download it from the page https://github.com/PrestaShop/ps_googleanalytics/releases/tag/v4.1.0 and upload it on your shop.
