### ISSUE TITLE
This file is not a module in valid ZIP format.

### ISSUE THREAD

**Issue by eugentum** [PrestaShop/ps_googleanalytics#98]
Sorry I ran `composer install` but it still doesn't work. Maybe I did something wrong.

1. I extacted zip file.
2. I ran `composer install` via powershell.
3. I ziped this again.

Set location was folder "ps_googleanalytics-dev".
![Снимок экрана 2021-07-27 215459](https://user-images.githubusercontent.com/80117839/127213067-a3067d4d-3234-45d7-8426-898791c75991.png)

**Comment by matks** [comment]
Hi @eugentum we released today ps_googleanalytics v4.1.0 module.

We attached a production-ready ZIP to the release, you can download it from the page https://github.com/PrestaShop/ps_googleanalytics/releases/tag/v4.1.0 and upload it on your shop. I tested it. This should allow you to solve your situation 😉
